### ISSUE TITLE
Ubuntu 13.10 登录提示 error creating ssl context() 

### ISSUE THREAD

**Issue by chuyik** [WizTeam/WizQTClient#212]
刚装了为知笔记linux版，输入完帐号密码后，谈了一个框，框名是验证账户失败，内容是error creating ssl context()，登录不上去，求原因。
PS. 我装了openssl libcrypto++8 libcrypto++-dev libssl-dev libssl0.9.8，还是不行。。。

**Comment by yangguang760** [comment]
同样遇到这个问题，请问楼上的同学解决了么？

**Comment by yangguang760** [comment]
已解决。

apt-get 会自动装i386的包，貌似调用64位的openssl有问题。
到http://ppa.launchpad.net/wiznote-team/ppa/ubuntu/pool/main/w/wiznote/ 下载amd64的包再次安装后解决

**Comment by chuyik** [comment]
@yangguang760 好久之前的问题了~其实现在已改用 evernote...
