### ISSUE TITLE
Can not move the application window out of the screen and multitab support on linux?

### ISSUE THREAD

**Issue by modten** [WizTeam/WizQTClient#251]
在 Linux 平台无法拖动窗口移出屏幕。
Version 2.1.13，Archlinux，XFCE

我常常需要开着几个窗口做笔记，比如一边看视频教程，一边做笔记。但是为知笔记不仅很难改变大小[1]，而且也不能移出屏幕或者响应窗口管理器的分屏功能[2]。这就导致使用小屏幕(1440)的我不得不一直在 Firefox 和 为知笔记 之间进行切换，因为当前窗口总是会被另一个窗口挡住，这让我感到相当不方便。视频缩太小了，看不清(还有一些非响应式的网页像百度百科，缩太小一些内容会被挡住，我需要不停得拖动横向滚动条)；为知笔记缩到最小，那笔记编辑区域就会被侧边栏挤得很小，我尝试隐藏侧边栏，但这并不能从根本上解决我的问题。

[1] 我需要将鼠标移到左上角，运气好的话可以改变大小，是否增加一个用来表示可以缩放窗口的鼠标状态。
[2] 这个问题，包括前面一个都是因为使用了 Frameless Window，这个是直接被窗口管理器忽略的，我写了几个Demo，最终确定 qt 的 move 包括 Xlib 的 xmovewindow 因为窗口管理器限制，是不能移动出屏幕边界的，但 qt 的 frameless window 通过 win + 鼠标拖动是可以移出屏幕边界的。
接着我尝试了几种方法来解决我的问题：
1. setWindowFlags(Qt::X11BypassWindowManagerHint|Qt::FramelessWindowHint);
可以移出屏幕了，新的问题来了：跟标题栏的 mousemove 事件冲突，移动有些抖动，并且窗口永远保持最前。
2. 去掉 FramelessWindowHint 标记，使用窗口管理器自带的标题栏，解决问题，未发现任何新问题，但是最好去掉标题栏的拖动功能，因为它已经没有意义了。
3. 查阅资料找到了 qt 论坛上，有人提出了这个问题：http://qt-project.org/forums/viewthread/46952
hualet 说道 发送 _NET_WM_MOVERESIZE 给窗口管理器解决此问题，但是我不知道该如何操作，是不是结合 X11BypassWindowManagerHint 修改一下就可以解决这个问题了呢？

目前我自己重新编译并且在使用有窗口标题栏的版本，可能可以同时解决这些 issue 的部分需求：#239 #233 
另外一个问题是有没有考虑支持像 Windows 版那样的多标签笔记查看或编辑操作，看了下最新的提交日志，似乎去掉了开启多个窗口实例，本来还想可以用这个实现多开，虽然不能改变大小也不是很方便，但同时只能打开单篇笔记感觉也不方便就是了。

**Comment by JackieLiu1** [comment]
针对无法移动出屏幕的问题，其实没有必要非要采用系统的主题，在FrameLess的模式下，可以通过调用XLIB的库进行设置即可，比如在MovePressEvent里面加入如下代码替换到自己写的窗体移动代码即可（注：原理就是用XLIB的更底层的函数替代掉自己写的moveWindow即可）
```c++
void System::MoveWindow(void)
{
	XEvent event;
	memset(&event, 0, sizeof(XEvent));
	const auto pos = QCursor::pos();

	Display *display = QX11Info::display();
	event.xclient.type = ClientMessage;
	event.xclient.message_type =
	    XInternAtom(display, "_NET_WM_MOVERESIZE", False);
	event.xclient.display = display;
	event.xclient.window = wid;
	event.xclient.format = 32;
	event.xclient.data.l[0] = pos.x();
	event.xclient.data.l[1] = pos.y();
	event.xclient.data.l[2] = 8;
	event.xclient.data.l[3] = Button1;
	event.xclient.data.l[4] = 1;

	XUngrabPointer(display, CurrentTime);
	XSendEvent(display, QX11Info::appRootWindow(QX11Info::appScreen()),
		   False, SubstructureNotifyMask | SubstructureRedirectMask,
		   &event);
	XFlush(display);
}
```
在想移动的的位置调用这个函数即可

**Comment by JackieLiu1** [comment]
注明：上面的所有部分都是Qt程序通用的，除了winId，这个就是mainwindow->winId()，主要看怎么传递过来。
