### ISSUE TITLE
Small visual problem

### ISSUE THREAD

**Issue by danielsanfr** [WizTeam/WizQTClient#252]
Popups that appear when information icons are clicked has no border or shadow.

Now:
![captura de tela 2014-10-21 00 21 48](https://cloud.githubusercontent.com/assets/3621711/4712689/12321ed2-58d2-11e4-8155-998ce7e097c0.png)

With delimiter:
![captura de tela 2014-10-21 00 21 48-new](https://cloud.githubusercontent.com/assets/3621711/4712691/16086aa2-58d2-11e4-8d7e-d27e5d36feed.png)

**Comment by WizLxn** [comment]
This problem has been fixed on version 2.1.15.

**Comment by danielsanfr** [comment]
So far for me is still not fixed :(
