### ISSUE TITLE
OS X Yosemite 输入法切换障碍

### ISSUE THREAD

**Issue by zrong** [WizTeam/WizQTClient#267]
具体表现为：

新建一个 Note 之后，无论如何切换输入法，都无法在 Wiz 的输入区域内输入中文。

必须完全退出 Wiz，再重新打开界面，才可以输入中文。

输入法切换问题在 OS X 10.9 上也存在。

**Comment by WizLxn** [comment]
问题在2.1.15版本中已修复。
