### ISSUE TITLE
Green tray icon

### ISSUE THREAD

**Issue by 876974** [WizTeam/WizQTClient#289]
I would like to using gray icon themes, the application icon in the system tray was as gray
![My tray](http://i.876974.ru/3m.jpg)

**Comment by WizLxn** [comment]
The color of system tray icon on Linux was changed to gray since version 2.1.15.

**Comment by 876974** [comment]
after the update client to 2.1.19 tray icon again changed, gray icon changed to application icon

**Comment by WizLxn** [comment]
The grey icon used before looked quite bad on some system. Until we design a new general icon，the icon of app would be used as tray icon.
