### ISSUE TITLE
Mac OSX下，文章的info无法编辑

### ISSUE THREAD

**Issue by wizcabbit** [WizTeam/WizQTClient#290]
Mac OSX下，点击文章的info（叹号）之后，无法编辑其中任何项目。

**Comment by WizLxn** [comment]
奇怪，之前回复过，但是没有没有显示回复的内容。
目前是这么设计的。有需要修改的项目吗？

**Comment by wizcabbit** [comment]
^_^ 个人认为，文章的meta信息至少URL可以修改比较好。
1. 并非所有的笔记都来自Wiz剪辑插件，复制粘贴来的内容也需要出处。我和周围几个朋友只能粘贴过来一段内容，然后在链接粘在笔记第一行~
2. 有道、Evernote等笔记的Mac实现里meta信息也是可以编辑的~

**Comment by rex-li** [comment]
+1 

Meta有修改的需求。

**Comment by wizcabbit** [comment]
新版已经可以修改了~ 赞速度~
