### ISSUE TITLE
点叉关闭窗口进程未退出

### ISSUE THREAD

**Issue by xgdgsc** [WizTeam/WizQTClient#292]
archlinux，gnome-shell, wiznote 2.1.14
我又没有开使用托盘的功能，为什么点关闭按钮程序不退出，让我到哪去关闭程序？只能任务管理器里终止了。

**Comment by WizLxn** [comment]
这个地方考虑不周。修正为如果没有显示托盘图标，关闭窗口的时候会退出程序。

**Comment by liuyaweii** [comment]
centos 7 xfce 运行wiznote没有系统托盘？

**Comment by shenchong721** [comment]
@xgdgsc 
我现在也是这个问题，archlinux WizNote 启动不了：
"QLocalSocket::connectToServer: Connection refused"
clear thread pool, threads count :  0

该怎么解决？？

**Comment by xgdgsc** [comment]
@shenchong721 这个bug早修复了，现在不应该还有这个问题吧，我这里archlinux启动正常。

**Comment by shenchong721** [comment]
@xgdgsc 谢谢！后来我用yaourt wiznote-qt4安装之后打开了，
但是pacman -Ｓ wiznote之后还是不行。。。已经把系统升级到最新了，可能是我们学校的源没有同步吧
