### ISSUE TITLE
添加代码格式化功能

### ISSUE THREAD

**Issue by lzjqsdd** [WizTeam/WizQTClient#294]
在Ubuntu下使用，也会经常整理一些代码，但是没有代码格式化这个功能，比较遗憾。

**Comment by WizLxn** [comment]
抱歉迟复，现在有一个插入代码的功能。在导航栏【格式】-【插入】-【插入代码】。暂时没有直接在编辑器中调整代码样式的功能。

**Comment by rex-li** [comment]
Mac wiz没有PHP语法支持，请问何时预期可以添加？谢谢。

**Comment by lzjqsdd** [comment]
恩，好的
