### ISSUE TITLE
osx下fn+left/right键应该跳转到行首/行末

### ISSUE THREAD

**Issue by xgdgsc** [WizTeam/WizQTClient#301]
osx下fn+left/right键现在是跳转到整个笔记的首/末，而其他程序一般的习惯是跳转到行首/行末。是在osx下fn+left/right测试的，linux下home/end无此问题。

wiznote 2.1.15, osx 10.10

**Comment by greatcl** [comment]
跳转到行首/行末用command+left/right，你在提issue的输入框里试下，也是这用command来组合的，fn加方向键是跳转到页首和页尾的。

**Comment by xgdgsc** [comment]
这样啊，我的错。
