### ISSUE TITLE
搜索结果中出现了刚刚更新的笔记

### ISSUE THREAD

**Issue by xgdgsc** [WizTeam/WizQTClient#305]
我刚打开为知笔记，这时后台在同步更新笔记数据。而我此时开始搜索一个关键词，出现了搜索结果的笔记列表。然后当后台同步更新笔记数据有笔记更新结果时，更新的笔记会出现在这个搜索结果的列表里，这是不对的，更新的笔记并没有包含搜索的关键词。

archlinux， wiznote2.1.16.

另外你们每次更新版本的时候麻烦去https://www.archlinux.org/packages/community/x86_64/wiznote/flag/ 标记一下过期，你们现在这种发布方式让人搞不清楚到底哪个是最新稳定版。

**Comment by mobi12** [comment]
会不会是搜索组件负责记录最近文档


来自 魅族 MX2

-------- 原始邮件 --------
发件人：xgdgsc <notifications@github.com>
时间：周六 4月11日 11:49
收件人：WizTeam/WizQTClient <WizQTClient@noreply.github.com>
主题：[WizQTClient] 搜索结果中出现了刚刚更新的笔记 (#305)

**Comment by WizLxn** [comment]
已修复
