### ISSUE TITLE
账户同步时头像未同步过来

### ISSUE THREAD

**Issue by ZRhinoceros** [WizTeam/WizQTClient#309]
问题描述：
    原账户在Windows下创建，已正确设置头像，Windows下正常显示。Ubuntu幻镜下安装Wiznote，同步信息时日记正确同步，但头像显示未设置。
系统环境：
    Ubuntu 3.16 x86_64
非常感谢Wiz能够支持Linux版本，大赞！
注：刚测试修改账户头像也无正确显示。

**Comment by WizLxn** [comment]
头像显示的是默认的灰色头像还是什么都没有？更新软件到2.1.19版本试一下。
