### ISSUE TITLE
ubuntu 12.04 LTS 更新2.2.4后无法粘贴图片

### ISSUE THREAD

**Issue by ParadiseDS** [WizTeam/WizQTClient#326]
更新2.2.4后，在libreoffice writer中可以正常粘贴图片，确认图片在剪切板中，但无法粘贴至wiznote内容，之前的版本试过是正常的，望修复

**Comment by tamlok** [comment]
我也有该问题。从浏览器中复制图片过来，可以粘贴，但是换另一台机器后，发现图片无法显示。

**Comment by WizLxn** [comment]
@ParadiseDS  图片的来源是什么？
简单的测试了一下，chrome浏览器和剪切板中的图片可以粘贴。 

@tamlok   粘贴完成之后保存笔记，可以打开网页版查看该篇笔记是否上传成功。如果网页版中看不到图片，说明图片保存或上传有问题。

**Comment by linbojin** [comment]
@WizLxn 你好，我的版本是ubuntu 14.04 64bit V2.2.4，一直喜欢用wiz的截图功能，今天发现我笔记里面的截图图片没有更新到服务器，网页版和ipad里面显示好几张都是？丢失，我本地显示正常，手动同步了好几次log说同步完毕，但是依旧网页版显示丢失。后来我只能本地把截图图片另存到桌面然后用添加图片的方式加入，同步才能识别这几张图上传成功。请问这是一个bug吗，同步无法识别截图图片，我甚至有几次发现重新打开本地笔记后，本地的图片也变啦，是被服务器端笔记覆盖了吗？然后我重复了一遍工作再截图。。。

**Comment by tamlok** [comment]
对，我有时候也会遇到这个问题。

在 2015年9月6日 下午6:17，linbo.jin <notifications@github.com>写道：

**Comment by WizLxn** [comment]
看样子像是保存图片的时候出现问题了，粘贴后在编辑器里面能够显示，说明粘贴没有问题。有可能是保存笔记时提取图片出现了问题。

如果本地显示正常，服务器上显示丢失，可能是图片链接到了一个本地的路径上面，可以复制图片链接看一下。

**Comment by tamlok** [comment]
图片有时候是连接到一个本地的临时目录中，如`/tmp/...`之类的。

在 2015年9月7日 上午10:27，WizLxn <notifications@github.com>写道：

**Comment by linbojin** [comment]
所以如果在还没有上传到服务器之前，重启了电脑，那么linux会自动清空这个/tmp/文件夹的，自然就丢失啦，正解！👍那么这个暂存图片目录是否可以自定义到其他路径呢？

**Comment by tamlok** [comment]
应该是已经上传了的。另外，Win客户端有时会出现在网页上复制粘贴的图片，其实是保存了一个到原网页图片的一个链接，而不是wiz自己的一个服务器链接。校园网里面是区分免费地址和收费地址的。因此，如果图片原网站是收费地址，在免费地址连接下则无法查看笔记的该图片。

在 2015年9月7日 上午10:43，linbo.jin <notifications@github.com>写道：

> 所以如果在还没有上传到服务器之前，重启了电脑，那么linux会自动清空这个/tmp/文件夹的，自然就丢失啦，正解！👍那么这个暂存图片目录是否可以自定义到其他路径呢？
>

**Comment by linbojin** [comment]
@WizLxn 我实验了几次，的确是显示错误的图片都是链接到了本地路径类似file:///tmp/WizNote/369861858.png。我看正确的同步过程大概是这样: 加入图片后，图片会被复制到本地地址里类似file:///tmp/WizNote/xxxxx. 然后选择同步后， 本地图片会被加入数据库，在原来的本地地址图片就被删除啦，可能是移动操作。但不知道怎么回事我的客户端一直没法正确同步，只是上传了本地连接地址，这个和他们说的复制网页图片只上传外部url，我觉得是同一个问题。如此一来服务器没有保存图片文件，其他客户端访问就没法显示图片啦。ubuntu, /tmp/wiznote这个目录里面的图片貌似还一直会被wiz程序定期清理，这么一来本地图片没了，本地显示也是找不到图片。这个问题能否尽快解决？现在我每次工作保存截图都会这样莫名图片显示错误，很烦恼。不知道这个不保存实际图片而只是保存url的原因是不是wiz服务器容量限制问题。每个月几百兆的空间用不完，只希望能把我们的图片源文件保存到服务器上，而不是链接地址。

**Comment by tamlok** [comment]
目前一个比较保险的方法就是另存为图片，然后插入图片。

在 2015年9月8日 下午1:58，linbo.jin <notifications@github.com>写道：

**Comment by linbojin** [comment]
是的，我也发现只能这样，但是这样比较麻烦。

**Comment by WizLxn** [comment]
正常情况下保存笔记的时候会把图片文件都提取出来和笔记内容一起打包，应该是这个环节出现问题了。会尽快检查一下这个问题，因为问题在我这边不会重现，可能需要大家帮忙测试一下。

**Comment by linbojin** [comment]
因为我在国外，会不会是网速问题？我又试了几次，发现是在exit
wiznote的时候全部清理了/tmp/wiznote/下面的图片的，所以如果没有打包成功，那么再次运行软件，本地显示也缺失啦。

**Comment by WizLxn** [comment]
@linbojin  和网速没有关系，上传笔记之前会把笔记保存打包。再次查看笔记的时候会从笔记文件里面解压出图片放到指定笔记的临时目录里面。类似 file:///tmp/WizNote/3f4ba1b7-a486-455e-b54e-a407273bd5a9/index_files/1859309440.png 这种样式。

可以新建一篇笔记，粘贴一张图片，然后切换到其他笔记再切换回来。这个时候会保存笔记，然后重新加载这篇笔记，如果重新加载之后的图片路径依然是file:///tmp/WizNote/369861858.png，说明没有保存成功。

如果能够重现这个问题，可以给你发一个测试版本，定位问题。

**Comment by linbojin** [comment]
嗯嗯，是的，和我看到的是一致的，我离线用了软件也是可以保存，切换回笔记后也是变成了解压后的路径。所以图片路径的问题是在本地打包的时候出现的，图片没有保存成功，于同步没有关系。在代码里面能加一步检测吗，图片类似/tmp/wiznote/xx的说明没有保存成功，再次保存，不然数据库只保存了这个临时地址，就会出错。我这几次使用没有重现前面的问题，再次遇到了发上来讨论。

**Comment by linbojin** [comment]
@WizLxn 下午写笔记，再次遇到问题，我测试发现加入图ctrl+s保存之后，软件会立即打包图片链接就会变成解压的长地址，这种情况就能正常保存。但是我的一篇笔记里面加入第6张第7张图片的时候（前面的图片以前都保存过啦）发现我即使ctrl+s图片地址也没法变成解压型的地址也就是打包失败。然后预料之中，web没法显示这两张图。不管再次保存同步都是如此也就是图片链接一致是临时地址，客户端应该默认觉得这个是最新的而不会重新去打包图片。所以问题出现在长时间编辑笔记或者说是在插入多幅图片之后。每次保存可否能重新打包没有打包成功的本地图片？

**Comment by WizLxn** [comment]
问题已经确定，是2.2.4中引入的问题。已修复，PPA已更新。
