### ISSUE TITLE
将图标右键功能中的“显示/隐藏主窗口”放在左键上

### ISSUE THREAD

**Issue by mudongliang** [WizTeam/WizQTClient#330]
![screenshot from 2015-09-04 22 38 04](https://cloud.githubusercontent.com/assets/6214861/9686287/c89ea6b2-5355-11e5-99a8-656c84c2ee95.png)
我用的是linuxmint Cinnamon。我对于wiznote的建议是，能不能将图标右键功能中的”显示/隐藏主窗口“移到左键上面？
直接点击左键就可以”显示/隐藏主窗口“，这样使用起来就更方便了！

**Comment by WizLxn** [comment]
有些麻烦，Qt提供的托盘图标固定的将菜单绑到了右键上面。需要考虑其他的实现方式。

**Comment by mudongliang** [comment]
我用的大多数应用程序是gtk程序，所以，没有想到这其中的问题。另外，我也没有具体编写过图形界面程序。只是觉得这样符合我的使用习惯，麻烦就算了！
