### ISSUE TITLE
mac 2.2.2版本 文件夹重命名不起作用比如 Work->work

### ISSUE THREAD

**Issue by bigpyer** [WizTeam/WizQTClient#338]
RT

**Comment by bigpyer** [comment]
描述下具体的场景:
问题1:我在手机app上重命名了某个文件夹，然后第二天在mac上执行了同步操作，重现了如Work(重命名前)和work(重命名后)两个文件夹，并且work文件夹里的笔记都是空的
问题2:已删除文件夹是自动被清理的吗？我因为上述操作直接删除了Work，导致丢了很多笔记。。。。

**Comment by WizLxn** [comment]
这个是2.2.2版本引入的bug，在后面的版本中修复了。
目前删除个人笔记的逻辑是会把本地的笔记直接删掉。想要找回的话，可以在已删除文件夹上面点击右键，选择恢复已删除笔记可以通过服务器恢复30天内删除的笔记。

**Comment by bigpyer** [comment]
已经更新，提供的删除找回也非常好用，谢谢！
