### ISSUE TITLE
Mac 版本的链接无法插入 Wiz 内部文章

### ISSUE THREAD

**Issue by zrong** [WizTeam/WizQTClient#339]
希望 Mac 版本的链接插入功能做到和 Windows 版本相同。

目前 Mac 版本的链接仅仅只能输入一个地址，而 windows 版本的链接功能可以插入 Wiz 的内部问题等。

**Comment by WizLxn** [comment]
是要插入一条可以跳转到其他笔记的链接吗？

**Comment by zrong** [comment]
是的，就是这个意思。

**Comment by WizLxn** [comment]
Mac端有两个方式可以插入笔记链接：
1. 把一篇笔记拖拽到编辑器里面，会插入一个链接。
2. 也可以在笔记列表上面点击右键，选择复制笔记链接，然后粘贴就可以了。
