### ISSUE TITLE
点击人头像下拉菜单的 打开网页版， 我的分享  在ubuntu   下面无法打开

### ISSUE THREAD

**Issue by joostshao** [WizTeam/WizQTClient#354]
点击人头像下拉菜单的 打开网页版， 我的分享  在ubuntu   下面无法打开

**Comment by WizLxn** [comment]
这是调用系统的浏览器打开一个网址，系统有没有设置默认的浏览器？

**Comment by joostshao** [comment]
you, chrome lastes version.

**Comment by EdwardYuan** [comment]
@joostshao  我试过了，ubuntu 15.04, Chrome 最新版本，能打开，但是要等很久，大概30s-1min左右

**Comment by joostshao** [comment]
恩，就是很慢，是不是api通信方面的延时？
