### ISSUE TITLE
2.3.2 for mac .md 格式的笔记不显示字体

### ISSUE THREAD

**Issue by Wyc0** [WizTeam/WizQTClient#363]
<span style="font-family: &#39;Comic Sans MS&#39;;"> html 可以看到有 comic sans 字体的 style 但是转换成 markdown 之后不显示

并且 markdown 格式的笔记转换成 html 查看之后再取消 html 格式, 此时只会显示 markdown 的代码没有样式加载出来

**Comment by WizLxn** [comment]
是切换到源码模式在切换回来markdown不渲染了？ 其他笔记有没有问题。

现在的版本增加的一些自定义样式。如果markdown模板里面没有详细的标明<p>等标签的字体属性，会使用新增的默认样式

**Comment by Wyc0** [comment]
对 就是切换到源码然后再切换回来不渲染 
![123](http://i4.tietuku.com/df38207d2a612c21.png)大概就是像这样 但是不是每次都会出现这种情况
不过多尝试几次, 任意笔记转换到html然后随意点击几下再切换回去均会出现这种情况 已经有好几篇变成这样了...
试过重启wiz无效, 不知道是否是我使用不当

**Comment by sdnian** [comment]
我也遇到同样的问题，每次发生就只好重新建立一个新的 markdown 笔记。

**Comment by Wyc0** [comment]
另外开始我说的那个字体的问题具体情况是这样的
![12](http://i4.tietuku.com/25b22db2f2f2a63e.png)
在html里面是有字体的
![](http://i4.tietuku.com/777f7d5bb015da07.png)
没渲染时也是有字体的
![](http://i4.tietuku.com/494814df5fc6dcd8.png)
渲染之后字体就没了

上一个版本wiz, 字体在渲染之后仍会存在
