### ISSUE TITLE
为知笔记mac2.3.2（2015.12.12 3：18）版经常崩溃问题

### ISSUE THREAD

**Issue by Zieng** [WizTeam/WizQTClient#370]
在移动笔记文件到另一个文件夹，以及导出笔记为pdf时都遇到过为知笔记程序崩溃。
但是并非每次执行上述操作都会程序崩溃。

**Comment by wiz-cuiguangbin** [comment]
再次启动时，如果有发送崩溃报告提示，请选择发送，以方便我们这边排查，谢谢。
