### ISSUE TITLE
centos下从源码编译安装报错

### ISSUE THREAD

**Issue by zhongxun1492** [WizTeam/WizQTClient#372]
系统环境centos 64bit
根据网站提供的方法，配套软件都安装成功
执行./centos-package.sh后编译报错，具体错误信息如下：
[ 68%] Building CXX object src/CMakeFiles/WizNote.dir/share/cppsqlite3.cpp.o
[ 68%] Building CXX object src/CMakeFiles/WizNote.dir/share/wizobject.cpp.o
/home/WizQTClient/src/share/wizmisc.cpp: In function ‘bool WizGetLocalUsers(QList<WizLocalUser>&)’:
/home/WizQTClient/src/share/wizmisc.cpp:2620: 错误：expected initializer before ‘:’ token
/home/WizQTClient/src/share/wizmisc.cpp:2710: 错误：expected primary-expression at end of input
/home/WizQTClient/src/share/wizmisc.cpp:2710: 错误：expected ‘;’ at end of input
/home/WizQTClient/src/share/wizmisc.cpp:2710: 错误：expected primary-expression at end of input
/home/WizQTClient/src/share/wizmisc.cpp:2710: 错误：expected ‘)’ at end of input
/home/WizQTClient/src/share/wizmisc.cpp:2710: 错误：expected statement at end of input
/home/WizQTClient/src/share/wizmisc.cpp:2710: 错误：expected ‘}’ at end of input
make[2]: *** [src/CMakeFiles/WizNote.dir/share/wizmisc.cpp.o] 错误 1

**Comment by wiz-cuiguangbin** [comment]
Qt编译成功了吗 ?
