### ISSUE TITLE
ubuntu Qt5编译不了

### ISSUE THREAD

**Issue by cposture** [WizTeam/WizQTClient#373]
CMake Error at /usr/share/cmake-3.2/Modules/FindQt4.cmake:1326 (message):
  Found unsuitable Qt version "5.5.1" from
  /home/cposture/software/Qt/5.5/gcc_64/bin/qmake, this code requires Qt 4.x
Call Stack (most recent call first):
  cmake/QtChooser.cmake:10 (find_package)
  lib/quazip/CMakeLists.txt:6 (include)
编译时 CMAKE参数为-DCMAKE_BUILD_TYPE=Debug,-DWIZNOTE_USE_QT5
问题出现在quazip上，但不知如何解决？

**Comment by WizLxn** [comment]
参数是 `cmake -DWIZNOTE_USE_QT5=YES -DCMAKE_BUILD_TYPE=Debug`
中间使用空格分隔

**Comment by cposture** [comment]
谢谢可以了！
最后总结一下：
系统：ubuntu 15.04
Qt：5.5.1
编译时，CMAKE 参数为 -DWIZNOTE_USE_QT5=YES -DCMAKE_BUILD_TYPE=Debug
调试时出现源码编译错误_mm_shuffle_epi8 (__m128i a, __m128i b) 重复定义，解决方法： #316 
运行时，出现WizQTClient-build/bin/cl_test-ascii does not exist. 解决方法：project->run configuration 改为WizNote即可
