### ISSUE TITLE
添加对 markdown 模式下 todo list 的支持

### ISSUE THREAD

**Issue by daicang** [WizTeam/WizQTClient#378]
当前 WizNote 的 markdown 模式还不支持 todo list 这样的语法:

``` markdown
- [ ] todo-1
- [ ] todo-2
- [x] done-1
```

希望开发人员能支持这样的语法. 当初就是因为支持漂亮的 markdown 转到的 WizNote (之前用过 Evernote, OneNote), markdown 的 todo list 这样写起来很方便, 希望提供支持! 谢谢

**Comment by wiz-cuiguangbin** [comment]
感谢反馈，已列入计划中，后续版本会支持。

**Comment by mrwangyu** [comment]
同样需要此任务，期待中。
