### ISSUE TITLE
wiznote在ubuntu下打开单独的一个文档,能不能全宽度显示？

### ISSUE THREAD

**Issue by codekissyoung** [WizTeam/WizQTClient#381]
有的时候还是能够全屏显示好一些，比如一张大图~

**Comment by codekissyoung** [comment]
![Uploading wiznote.png…]()

**Comment by codekissyoung** [comment]
截图一直传不上来.....

**Comment by WizLxn** [comment]
使用独立窗口打开笔记后，独立窗口不能全屏吗？

**Comment by tamlok** [comment]
窗口可以全屏，但是文档的宽度却不能占完整个屏幕～～

2016-03-21 23:20 GMT+08:00 WizLxn <notifications@github.com>:

**Comment by codekissyoung** [comment]
+1 窗口可以全屏，但是文档的宽度却不能占完整个屏幕～～
