### ISSUE TITLE
最新版本是多少～，官方2.3.2，这里2.1.12 

### ISSUE THREAD

**Issue by cnlinjie** [WizTeam/WizQTClient#387]
官网上的是2.3.2 版本(2015-12-03) 
这边的tag怎么只有2.1.12 ，这个版本怎么规划的～ 
目前Fedora23用的是2.3.1 ，有个BUG，加密的笔记输入密码就闪退～，分别在官方和QQ群都反馈过了～
回复邮件是说：升级到2.3.2 ～
这要怎么升级，dnf 和 yum 里面最新的是 2.3.1 ，在怎么update都是这个版本～
如果用源码编译，github这边的源码，版本显示让我心里没底～
@wizcn 
@WizTeam

**Comment by cnlinjie** [comment]
@WizLxn

**Comment by 1dot75cm** [comment]
wiznote 是 2.3.1-1.gitfdd16c9.fc23
wiznote-beta 是 2.3.2-1.git5976b84.fc23 @cnlinjie

**Comment by cnlinjie** [comment]
@1dot75cm  依旧闪退～，不知道日志文件在哪，为提取出来给你们

**Comment by cnlinjie** [comment]
@1dot75cm  目前安装得版本是2.3.2 beta版～
依旧一输入密码就闪退，最糟糕得在于没人任何提示～，所以无法知道是什么冲突还是～
@wizcn  @WizTeam  @WizLxn

**Comment by 1dot75cm** [comment]
Linux 客户端貌似无法生成 加密证书。提示 @cnlinjie 
> 未发现加密证书，请从Windows客户端创建加密证书。

**Comment by cnlinjie** [comment]
@1dot75cm 
wiznote-beta: secblock.h:151: void CryptoPP::NullAllocator<T>::deallocate(void*, CryptoPP::NullAllocator<T>::size_type) [with T = unsigned int; CryptoPP::NullAllocator<T>::size_type = long unsigned int]: Assertion `false' failed.

是这个么～
那要到Windows那边生成么？需要怎么做呢～

**Comment by 1dot75cm** [comment]
我没用过加密笔记。不知道为何 Linux 下无法生成证书。如果某个版本解决了这个问题，我会试图更新。 @cnlinjie 

另外，如果您有敏感信息，建议不要写入云笔记中。

**Comment by cnlinjie** [comment]
@1dot75cm
好的。
我去问下其他朋友能不能用～
