### ISSUE TITLE
兄弟说句题外话  你们对OSX软件的开发投入真不给力

### ISSUE THREAD

**Issue by liuzexin** [WizTeam/WizQTClient#392]
版本半年没有更新  至少我认为你们没有用心去做好这个产品在OSX

**Comment by wiz-cuiguangbin** [comment]
之前集中在开发Windows版，上周Windows已发新版，目前Mac版正在开发中。

**Comment by Misfit-John** [comment]
感觉mac版都不是特别注重，有道的mac版也是搓得要命。另外，想问下你们mac下面怎么开发的。。。那个qt creator在我的mac下面的体验只能用惨绝人寰来形容。

**Comment by zhoujoey** [comment]
自己不会用别说软件问题，先看懂软件说明书吧

**Comment by Misfit-John** [comment]
楼上的大兄弟我已经不是第一次在这个project下面见到你了。你是纯粹来找茬？谁告诉你不会用了？竞争对手请来的专业黑？嗯？

**Comment by mudongliang** [comment]
这是要逼我们转移客户端的节奏吗？

**Comment by liuzexin** [comment]
不说了  说多了都是泪已经转印象了
