### ISSUE TITLE
你们的员工态度怎么这么差？

### ISSUE THREAD

**Issue by Jun995** [WizTeam/WizQTClient#394]
看下这个issues
>https://github.com/WizTeam/WizQTClient/issues/391

这位zhoujoey对待用户的态度是不是有点问题？而且面对的还是可能给你们的产品贡献代码的用户。
我也算是你们的忠实用户了，用了很久，也买了你们的会员服务。这次来看issue的目的也是看看有没有什么bug可以自己尽一份力。可是看到上面那段讨论真是倍感失望，你们对待用户的态度竟然是这样的。

大概也有人来回复我爱用不用吧。

**Comment by Misfit-John** [comment]
其实吧。。。你确定那是为知的员工吗。。。我在这个issue 下面回复的，#392 ，林子大了，真的什么鸟都有。。。你点进去看他的public activity，除了在issue区comment，有提交一条代码？另外跪求怎么在最新版本mac OSX下面用qt。。。真的很不好用。。。。还是说有其它绕过的办法。

**Comment by Jun995** [comment]
@Misfit-John 好吧，看着还真像是专门来黑的。。我用linux的，不太清楚mac上的情况，qt官网的开发包装上试下吧

**Comment by Misfit-John** [comment]
就是官方的qt包。。。官方那个安装包装了之后运行很慢，估计跟mac对X的支持有关吧。反正体验很长。还是不够了解qt，不然可以考虑用xcode编写的

**Comment by WizTeam** [comment]
你好，zhoujoey不是公司员工。  请原谅开源网友
