### ISSUE TITLE
为 debiancn 提供 wiz 官方打包请求

### ISSUE THREAD

**Issue by lishoujun** [WizTeam/WizQTClient#431]
Debian 中文社区提供了一系列软件，可作为对 Debian 官方仓库的一个补充， 其目的之一是改进 Debian 中文用户在 Debian 系统上的使用体验。
软件源地址：http://repo.debiancn.org
git地址：https://github.com/debiancn/repo

目前已经在该项目下发了issues：https://github.com/debiancn/repo/issues/47

希望为知能够提供一下官方支持 不胜感激！

**Comment by hosiet** [comment]
请修改 issue 名称，debiancn 社区与官方软件源无关。

如果需要将其放入官方源，请去 Debian bug 追踪系统提交请求，向名为`wnpp`的虚拟软件包提交类别为“RFS”(Request for package) 的请求进行登记，等待感兴趣的人士进行打包工作。

**Comment by lishoujun** [comment]
@hosiet 你好
已经修改了名称，您看这样可以么？

**Comment by hosiet** [comment]
没问题，下面我们需要等待感兴趣人士完成打包工作。这个 issue 可以追踪进展。
