### ISSUE TITLE
为什么官方的ppa不更新了呢?如果不愿意更新，就不要开放源码出来了

### ISSUE THREAD

**Issue by joostshao** [WizTeam/WizQTClient#439]
很简单的道理，我想很多人都有这个疑问

**Comment by levinit** [comment]
同问（帮deb用户）。源码放出来还是必要的，arch的community源中就有wiznote。

**Comment by 7hil** [comment]
因为 ppa 不更新就开源就没意义了吗，无法理解这种逻辑。
开源了，没更新 ppa，你可以选择自力更生自己维护一个 ppa，感觉官方并没有义务维护这个东西吧。
