### ISSUE TITLE
为知笔记编辑区域无法输入中文！

### ISSUE THREAD

**Issue by levinit** [WizTeam/WizQTClient#443]
为知笔记编辑区域无法输入中文！**正文区域无法切换出fcitx中文输入法**，**其余区域使用正常**，如标题栏、搜索栏以及树状目录（重命名目录名正常输入中文）。

**其余qt程序均能正常输入中文。**

系统ArchLinux（滚动最新），输入法fcitx-pinyin。

可能是最近升级的qt。（百度贴吧网友提示的，我记不得有什么时候开始不能输入了。）
为知笔记的贴吧也有用户反应，参看：
http://tieba.baidu.com/p/4960116965

---
暂时用qt5.7的wiznote：
http://www.wiz.cn/compile-client.html
下载：http://download.qt.io/official_releases/qt/5.7/5.7.0/qt-opensource-linux-x64-5.7.0.run

**Comment by ahuixia** [comment]
我也是碰到这个问题，！！！！！！！！！！！！！！！
同arch

**Comment by kalxd** [comment]
https://bugreports.qt.io/browse/QTBUG-58362
看来需要上游来解决。

**Comment by gmaso** [comment]
centos7.3，qt5.8，ibus1.6.91，wiznote的master分支，也是遇到这个问题

**Comment by freealong** [comment]
同一个arch
同一个问题

**Comment by fluviusmagnus** [comment]
Manjaro 滚到最新现在好像好了。多方求证。

**Comment by joostshao** [comment]
同样的问题

**Comment by xi-guan** [comment]
同样的问题

**Comment by HomeLH** [comment]
同样的问题，有没有好的解决方法

**Comment by frankfancode** [comment]
问题没有解决，为什close

**Comment by huangnengCSU** [comment]
没有解决怎么closed?

**Comment by MENG2010** [comment]
Ubuntu 20 + fcitx-pinyin + 官网下载的最新的 WizNote。不能输入中文，甚至不能切换输入法。
同上疑问，问题没有解决也没有任何解释（比如，依赖系统底层的支持; 或者干脆WizNote 就不打算支持Ubuntu 下的中文输入），怎么就直接关了呢？

**Comment by MENG2010** [comment]
https://www.ubuntukylin.com/ukylin/forum.php?mod=viewthread&tid=191647

**Comment by altairwei** [comment]
试试我维护的 [WizNotePlus](https://github.com/altairwei/WizNotePlus) ，没有中文输入问题，支持多标签浏览、外部编辑器等新特征。

**Comment by jpfss** [comment]
ubuntu20.04 自己使用了fcitx中配置了百度输入法，为知笔记方法确实不能输入中文
