### ISSUE TITLE
New release?

### ISSUE THREAD

**Issue by feddasch** [WizTeam/WizQTClient#444]
Hi, I'm trying to package this program for [Solus](https://solus-project.com), but the latest release was from 2015 and it's a bit broken for actual systems (there are a lot of problems with GCC 6). Since we cannot package from tarballs from commits and seems like the 2.4.0 version it's official (but still a commit only), can you make a proper tag and release?

Thanks in advance.

**Comment by levinit** [comment]
http://www.wiz.cn/compile-client.html
download：http://download.qt.io/official_releases/qt/5.7/5.7.0/qt-opensource-linux-x64-5.7.0.run
now,you should pay ￥6(rmb)/month.
