### ISSUE TITLE
Cannot log in via WizNote Client (Ubuntu)

### ISSUE THREAD

**Issue by MENG2010** [WizTeam/WizQTClient#459]
I suddenly cannot log into my account via WizNote client (Ubuntu). I am sure that I input CORRECT account and password since I can log in via Mobile Client and Web WizNote. I am not sure whether it's because that I created a group. 

BTW, I selected to sign in WizNote Server as usual.

**Comment by MENG2010** [comment]
It's because I enabled the new sync mode. And I just solved this problem by re-compiling the latest version of WizNote on my Ubuntu.

This can be closed now. Thanks.

**Comment by Vishal040393** [comment]
I am new to Ubuntu. and recently installed Wiznote as an alternative to Evernote. But I have similar login problem as you mentioned. Will you please help me how you solved the issue?
