### ISSUE TITLE
编译完成后有些地方字体好小

### ISSUE THREAD

**Issue by ljhui** [WizTeam/WizQTClient#474]
按照官方的教程编译倒是成功，就是标题和内容都无法输入中文，参考了 #423 ，编译后的倒是解决了中文的问题，不过在fedora24 高分屏下有些字体好小，如下图
![screenshot from 2017-06-29 18-43-04](https://user-images.githubusercontent.com/16174049/27684034-dcee39fa-5c8d-11e7-9498-b15f7736e99a.png)
标题和编辑器工具选项都太小，这怎么解决？
另外写的markdown文件书写时字体正常,一旦markdown渲染后字体就变小，笔记里保存的剪裁的文章也字体太小，没法看，还有帮助中的用户反馈显示404

**Comment by yanhuixie** [comment]
@ljhui 可以正常同步吗？
