### ISSUE TITLE
Linux版本笔记编辑器中文字输入bug反馈

### ISSUE THREAD

**Issue by heygrain** [WizTeam/WizQTClient#478]
使用环境：Deepin 15.4

在笔记编辑器中输入中文时，如果在输入法中打错了词想删掉，会残留最后一个字母，如图： 
![_ _20170714125020](https://user-images.githubusercontent.com/8529601/28199171-30279bf2-6896-11e7-9119-5b191204e42b.gif)

而在新建目录，给目录起中文名时则不会出现这个问题：
![_ _20170714125332](https://user-images.githubusercontent.com/8529601/28199172-3035f184-6896-11e7-8dc0-efda3ef71116.gif)

然后不知道这个编辑器为什么在输入法输入的时候会把拼音先输入进去，其他应用，比如chrome的地址栏，是不会这样的：
![_ _20170714125448](https://user-images.githubusercontent.com/8529601/28199173-3037e868-6896-11e7-87dc-982068f252c1.gif)

**Comment by whuwangyong** [comment]
楼上，你是自己编译的还是deepin商店下载的？我deepin商店下载的2.5.5.1 版本使用异常。

**Comment by seifer08ms** [comment]
我估计是深度软件源里的版本的问题吧，建议自己编译个试试。。。
