### ISSUE TITLE
为了linux平台才花钱买的，结果linux还要编译安装。。。。。

### ISSUE THREAD

**Issue by hujianxin** [WizTeam/WizQTClient#498]
对这个垃圾公司太失望了，赶紧倒闭吧

**Comment by Dollyn** [comment]
关键是不能退钱

**Comment by DennisWong** [comment]
要钱无所谓，自己编译也无所谓。LZ钱也掏了，编译也成功了，结果不能同步。我只能呵河了

**Comment by DennisWong** [comment]
网上有打包好的版本，但是只能用root登陆，非root用户登录，则不能则不能同步笔记

**Comment by whuwangyong** [comment]
关键是编译出来的东西使用正常也就罢了。结果跟Windows版本不能比啊，很多功能没有。唉，用 Linux 困难重重。

**Comment by seifer08ms** [comment]
确实有同感，感觉有点开源软件的完成度，又没有商业软件的服务。

**Comment by hujianxin** [comment]
@seifer08ms 好点的（正常点的）开源项目才不会这样呢，好点的开源项目各种安装包都会提供，而且兼容性很好

**Comment by seifer08ms** [comment]
@hujianxin ,(⊙﹏⊙)b汗。这么要求的话连开源社区版都赶不上了。。。
其实我最感觉逗逼的是，看见有用户提了很多人都想要的判定重复的feature，wiz就简单敷衍说靠标题排序不就行了，都一点没和用户客气下说会认真考虑？真有意思，什么笔记自动分类等智能功能就更不用奢望了。

**Comment by hujianxin** [comment]
@seifer08ms 就是一个竭泽而渔的骗钱企业，我已经不用这个软件了

**Comment by seifer08ms** [comment]
@hujianxin ,求推荐现在用的

**Comment by hujianxin** [comment]
@seifer08ms Evernote，因为既然Linux平台下没什么好用的同步笔记，我就直接用网页版了。我平时mac，所以在mac下面用Evernote，在Linux下面直接用网页版。

说真心话，比为知笔记好看很多

**Comment by seifer08ms** [comment]
@hujianxin 他的网页截取功能做的怎么样？

**Comment by hujianxin** [comment]
@seifer08ms 比为知笔记好用很多倍

**Comment by seifer08ms** [comment]
@hujianxin ,上网查了下好像免费的就够用了。wiznote笔记迁移过去的效果还好吧，我的也快过期了，也打算远离这个烂摊子了哼哼。

**Comment by hujianxin** [comment]
@seifer08ms 迁移挺麻烦的，你如果是windows平台的话，估计还有方法（需要查查），别的平台迁移很麻烦，我打算用到的时候再迁移。

**Comment by Jason2Ray** [comment]
这款软件的Linux版本确实是一个烂摊子，我买了会员，用了半年，出现各种问题，直接放弃。

**Comment by jinzw1993** [comment]
能不能发布一个原来不用编译的那一版啊.至少还能用啊 .

**Comment by cnlinjie** [comment]
@jinzw1993  因为Linux平台的版本太多，环境也大都不一样，所以很难编译出一个大家都能通用的版本。
这是需要理解的，你看搜狗输入法现在还只支持Debian系列，而且还是Debian里面的Ubuntu，你看网易云音乐如此。
在这么多的企业当中，你想想看除了 为知 出了Linux版本，哪个公司出了？哪个公司都不会出，不敢出，因为他们不能像为知这样把源代码直接开源出来，但是不开源出来，他们又没有办法为每个平台编译一个可以用的版本，所以他们索性就不做了。而且Linux受众面还小，吃力不讨好，为什么要做？
所以矮子里面拔高个，为知真的算是良心产品了。

**Comment by hujianxin** [comment]
@cnlinjie 做不做跟良不良心是两码事，不做可以，做了做不好也可以，但是收了钱做不好，就是不良心了。

**Comment by seifer08ms** [comment]
@cnlinjie 
吃力不讨“好”？钱不就是最大的“好”？
说实话用户花钱不是为了要源代码，没那时间去研究，要不然都去搞Leanote就OK了。目前的开源和闭源软件，号称支持linux的大部分都有Ubuntu、centos等安装包。就因为其他云笔记的公司怎么样，所以wiz做到目前这样程度就算是对付费的用户大恩大德了吗？这“良心”也非常有限。
要用户理解wiz，wiz面对用户时那种敷衍态度有想过真正去理解用户吗？

**Comment by cnlinjie** [comment]
@hujianxin 
首选你付的钱不是单纯Linux端的，iOS/Android/Windows 都是可以用的，如果单纯Linux 收费，那站在这点可以说。

接着，不是他不想做好，是Linux这个分裂的太严重了，他能做到最大的努力就是开源。
而如果让为知投入巨大的成本去解决这个问题，对公司来说不实际。

他也像其他云笔记一样，只提供网页版的。

所以我说太“良心”是基于这点。

在云笔记平台，除了为知，谁做到了？

**Comment by cnlinjie** [comment]
@seifer08ms  看我上一条回复。
能做到Ubuntu 和 Centos 分别打包的基于依赖外部环境较小，如果依赖外部环境太多，目前除了Docker能解决外，其他的解决不了（至少我所了解到的）。 

然后呢？就算搞好了，其他用户怎么说？是不是搞歧视？凭什么都是付费用户你只搞了Ubuntu和Centos的安装包，我这本版本你的你不搞？ 

不说了，如果大家都是基于“收费” 这点说话，我们建议，Linux版本搞免费吧。

不过，这会不会打击Linux的版本？

**Comment by hujianxin** [comment]
@cnlinjie 那你知道的实在是太少了，我告诉你有多少软件同时支持Ubuntu，Centos。

+ https://github.com/atom/atom
+ https://github.com/Microsoft/vscode
+ https://github.com/zealdocs/zeal
+ https://www.jetbrains.com/
+ https://www.google.com/chrome/browser/desktop/index.html
+ https://www.mozilla.org/en-US/firefox/
+ https://www.wireshark.org/download.html
+ https://www.dropbox.com/install
+ https://www.jianguoyun.com/s/downloads/linux

我随随便便想了想自己使用的软件，都同时支持Ubuntu 和 Centos。

另外，你也别跟我扯什么歧视不歧视，Debian、RH、Arch系列占据了Linux桌面的绝大多数市场，搞好了这个，绝对不会有人在抱怨了。

**Comment by hujianxin** [comment]
@cnlinjie 另外，这位辩论家，你就别为为知笔记在这里辩论了，在企业面前，用户永远都是弱势，为自己争取点利益吧，人家企业还没说话呢，你到快，先为企业来说话了

**Comment by jinzw1993** [comment]
@cnlinjie  的确公布代码很牛逼，但是你也要面向客户啊，我花钱是买服务不是买代码。而且以前有可以用的安装包。为什么不再公布出来啊。因为他有ubuntu版本的所以 我才充了会员。如果没有简易版本我就不打算充会员了。因为对于编译来说 和没有几乎一样。而且Android studio的Linux版本很好用。人家不公布代码。

**Comment by cnlinjie** [comment]
@hujianxin   我不是Linux平台的开发者，不过我从开发者的角度来说，如果这事情很容易做到，那企业肯定很乐意做，我想 @WizTeam  下开发者，能否告知下为何不提供具体的安装包，希望能为你我解惑。
@WizTeam   

@jinzw1993  同理，希望 @WizTeam  能解释下。

然后，我觉得不管讨论何种东西，都希望可以少点诅咒和负气，看帖子（暂且这么论），一进来就看到“对这个垃圾公司太失望了，赶紧倒闭吧”，接着是各种抱怨。

我理解，在Linux版本下确实不太好安装使用，如果可以，我也希望为知能做的更好，但是希望能够理智一点。

说到这，也确实希望为知的开发团队能公布下提供各平台的安装包的初衷。

**Comment by seifer08ms** [comment]
@cnlinjie 

之所以负气还不是因为正面渠道阻塞后，积累而至？另外“诅咒”也是一种猜测，还没有几个公司能不和付费用户客套下就直接拒绝需求（ 大部分都是说会认真考虑然后不做，而为知是直接表示不做，有一种用户提的需求都是无理的态度），唯一合理的解释不就是公司已经快怎么样了，所以根本也没意愿去理会维持用户；或者是给员工的待遇很差导致服务态度非常消极，这样还是公司前景堪忧，导致的结果还是公司迟早要怎么样。

而且即使编译很容易不需要依赖，Linux版本有些功能也不完全吧，难不成让用户看着代码加功能开发吗。。。

**Comment by IsoaSFlus** [comment]
我觉得打包这个事情吧。。。Linux的发行版虽然众多，但维护者也众多，完全可以只打包一个发行版，比如deb系的。其他的发行版打包交给社区的人自愿打包就行了。网易云好像也是这样做的。
