### ISSUE TITLE
Wiz Client can't display note content on Ubuntu 17.10 . It works fine on ubuntu 17.04 before upgrade.

### ISSUE THREAD

**Issue by fartisan** [WizTeam/WizQTClient#507]
Wiz Client can't display note content on Ubuntu 17.10 .
When a note is selected on left pane , ther's only a title displaying at right pane , note content can't display , and nothing happened if "Edit" button is pushed .

 It works fine on ubuntu 17.04 before upgrade. Wiz been re-built after upgrade , problem still exists.

Here is the terminal output:
 
⇒  ./WizNote
[WARNING]: QWidget::setLayout: Attempting to set QLayout "" on QMainWindow "", which already has a layout ((null):0, (null))
[WARNING]: QFont::setPixelSize: Pixel size <= 0 (-5) ((null):0, (null))
[1123/150549:ERROR:browser_main_loop.cc(217)] Running without the SUID sandbox! See https://chromium.googlesource.com/chromium/src/+/master/docs/linux_suid_sandbox_development.md for more information on developing with the sandbox on.
/home/qt/work/qt/qtwebengine/src/3rdparty/chromium/sandbox/linux/seccomp-bpf-helpers/sigsys_handlers.cc:**CRASHING**:seccomp-bpf failure in syscall 0281
Received signal 11 SEGV_MAPERR 00000c003119
#0 0x7fd31bb11aee <unknown>
#1 0x7fd31bb11eab <unknown>
#2 0x7fd3176b8150 <unknown>
#3 0x7fd31c2fb0a8 <unknown>
#4 0x7fd31c45cc5e <unknown>
#5 0x7fd3176b8150 <unknown>
#6 0x7fd316ae6c87 epoll_pwait
#7 0x7fd31cfed8c0 <unknown>
#8 0x7fd31cfebb12 <unknown>
#9 0x7fd31bb08e1e <unknown>
#10 0x7fd31bb42668 <unknown>
#11 0x7fd31bb2cc25 <unknown>
#12 0x7fd31bb5abe1 <unknown>
#13 0x7fd31bb57287 <unknown>
#14 0x7fd3176ac7fc start_thread
#15 0x7fd316ae6b0f clone
  r8: 0000000000000002  r9: 00007fd309a7552c r10: 0000000000000000 r11: 0000000000000246
 r12: 00007fd309a75530 r13: 0000000000f4bd70 r14: 00007fd309a75580 r15: 0000000000f32440
  di: 0000000000000001  si: 00007fd31dbf1686  bp: 00007fd309a75580  bx: 000000000c003119
  dx: 000000000c000000  ax: 000000000c003000  cx: 00007fd3176b6cc0  sp: 00007fd309a75530
  ip: 00007fd31c2fb0a8 efl: 0000000000010202 cgf: 002b000000000033 erf: 0000000000000006
 trp: 000000000000000e msk: 0000000000000000 cr2: 000000000c003119
[end of stack trace]
[WARNING]: QObject::connect: No such signal WizDocumentWebViewPage::actionTriggered(QWebEnginePage::WebAction) in /home/fire/projects/WizQTClient/src/WizDocumentWebView.cpp:139 ((null):0, (null))
/home/qt/work/qt/qtwebengine/src/3rdparty/chromium/sandbox/linux/seccomp-bpf-helpers/sigsys_handlers.cc:**CRASHING**:seccomp-bpf failure in syscall 0281
Received signal 11 SEGV_MAPERR 00000c003119
/home/qt/work/qt/qtwebengine/src/3rdparty/chromium/sandbox/linux/seccomp-bpf-helpers/sigsys_handlers.cc:**CRASHING**:seccomp-bpf failure in syscall 0281
Received signal 11 SEGV_MAPERR 00000c003119
#0 0x7fd31bb11aee <unknown>
#1 0x7fd31bb11eab #0 0x7fd31bb11aee <unknown><unknown>
#1 0x7fd31bb11eab <unknown>
#
2# 20x 7fd3176b81500x 7fd3176b8150<unknown> <unknown>

##33  0x0x7fd31c2fb0a87fd31c2fb0a8  <unknown><unknown>

##44  0x0x7fd31c45cc5e7fd31c45cc5e  <unknown><unknown>
#
5# 50x 7fd3176b81500x 7fd3176b8150<unknown> <unknown>
#
6# 60x 7fd316ae6c870x 7fd316ae6c87 epoll_pwaitepoll_pwait

##77 0x 7fd31cfed8c00x 7fd31cfed8c0<unknown> <unknown>
#8 0x7fd31cfebb12 <unknown>
#8 0x7fd31cfebb12 <unknown>
#9 0x7fd31bb08e1e <unknown>
#9 0x7fd31bb08e1e <unknown>
#10 0x7fd31bb42668
#10 0x7fd31bb42668 <unknown><unknown>
#11 0x7fd31bb2cc25 <unknown>
#11 0x7fd31bb2cc25 <unknown>
#12 0x7fd31bb5abe1 <unknown>
#12 0x7fd31bb5abe1 <unknown>
#13 0x7fd31bb57287 <unknown>
#13 0x7fd31bb57287 <unknown>
#14 0x7fd3176ac7fc start_thread
#14 0x7fd3176ac7fc start_thread
#15 0x7fd316ae6b0f clone
#15 0x7fd316ae6b0f clone
  r8: 0000000000000002  r9:
00007fd309a7552c  r8:  r10: 00000000000000020000000000000000  r9:  r11: 00007fd309a7552c0000000000000246 r10:
0000000000000000 r12:  r11: 00007fd309a755300000000000000246 r13:
0000000000f4be90 r12:  r14: 00007fd309a7553000007fd309a75580 r13:  r15: 0000000000f4bdf00000000000f32420 r14:
00007fd309a75580  di:  r15: 00000000000000010000000000f32430  si:
00007fd31dbf1686  di:   bp: 000000000000000100007fd309a75580  si:   bx: 00007fd31dbf1686000000000c003119  bp:
00007fd309a75580  dx:   bx: 000000000c000000000000000c003119  ax:
000000000c003000  dx:   cx: 000000000c00000000007fd3176b6cc0  ax:   sp: 000000000c00300000007fd309a75530  cx:
00007fd3176b6cc0  ip:   sp: 00007fd31c2fb0a800007fd309a75530 efl:
0000000000010202  ip:  cgf: 00007fd31c2fb0a8002b000000000033 efl:  erf: 00000000000102020000000000000006 cgf:
002b000000000033 trp:  erf: 000000000000000e0000000000000006 msk:
0000000000000000 trp:  cr2: 000000000000000e000000000c003119 msk:
0000000000000000[end of stack trace]
 cr2: 000000000c003119
[end of stack trace]
[WARNING]: QSslSocket: cannot resolve SSLv2_client_method ((null):0, (null))
[WARNING]: QSslSocket: cannot resolve SSLv2_server_method ((null):0, (null))
[INFO] 本地版本是最新版
[INFO] [Sync] "----------同步开始----------"
[INFO] [Sync] "连接服务器"
[INFO] [Sync] "登录"
[INFO] [Sync] "获取企业群组信息"
[INFO] [Sync] "获取群组信息"
[INFO] [Sync] "数据库数目: 1"
[INFO] [Sync] "下载设置"
[INFO] [Sync] "下载消息"
[INFO] [Sync] "上传消息"
[INFO] [Sync] "同步群组用户"
[INFO] [Sync] "----------同步个人笔记----------"
[INFO] [Sync] "当前数据库编号: 0"
[INFO] [Sync] "开始群组: "
[INFO] [Sync] "连接服务器"
[INFO] [Sync] "获取服务器信息"
[INFO] [Sync] "获取已删除列表"
[INFO] [Sync] "未改动，跳过"
[INFO] [Sync] "上传已删除列表"
[INFO] [Sync] "未改动，跳过"
[INFO] [Sync] "上传标签"
[INFO] [Sync] "未改动，跳过"
[INFO] [Sync] "上传样式"
[INFO] [Sync] "未改动，跳过"
[INFO] [Sync] "上传笔记"
[INFO] [Sync] "未改动，跳过"
[INFO] [Sync] "未改动，跳过"
[INFO] [Sync] "同步设置"
[INFO] [Sync] "上传附件"
[INFO] [Sync] "未改动，跳过"
[INFO] [Sync] "下载标签"
[INFO] [Sync] "未改动，跳过"
[INFO] [Sync] "下载样式"
[INFO] [Sync] "未改动，跳过"
[INFO] [Sync] "下载笔记"
[INFO] [Sync] "未改动，跳过"
[INFO] [Sync] "同步设置"
[INFO] [Sync] "同步设置"
[INFO] [Sync] "下载笔记参数"
[INFO] [Sync] "未改动，跳过"
[INFO] [Sync] "下载附件"
[INFO] [Sync] "未改动，跳过"
[INFO] [Sync] "完成群组: "
[INFO] [Sync] "----------同步群组----------"
[INFO] [Sync] "----------下载笔记内容----------"
[INFO] [Sync] "----------同步完成----------"

here is a snapshot of the blank display when a note is selected:
![default](https://user-images.githubusercontent.com/8855803/33164053-23256a5e-d06c-11e7-867c-4f80ef46ba3f.png)

**Comment by fartisan** [comment]
BTW, I'm also a paid user , if it helps to solve this issue :D

**Comment by Linuxea** [comment]
I also encounter this problem, then I download the deb file from package and dpkg -- install, but it also encounter the password error problem, WTF

**Comment by zliu-fd** [comment]
WizNote --disable-seccomp-filter-sandbox
这样启动可以解决这个问题，我也遇到这个问题，看起来像是glibc升级之后的兼容问题。
https://bbs.archlinux.org/viewtopic.php?id=229859

**Comment by fartisan** [comment]
@zliu-fd 测试好用，输入法sunpinyin也可以输入中文，谢谢
