### ISSUE TITLE
可以解决ubuntu18.04  libssl 依赖或重新打包下 WizNote-2.5.9-x86_64.AppImage 吗

### ISSUE THREAD

**Issue by Archer456** [WizTeam/WizQTClient#540]
可以解决或重新打包下 WizNote-2.5.9-x86_64.AppImage 吗?
这个版本,在最新的ubuntu18.04 的环境下,会有依赖冲突.

问题表象: 无法登录或者同步

临时解决: sudo apt install libssl1.0-dev

问题: buntu 18.04 是 libssl 默认版本是 1.1.0
而wiznote 依赖的是 libssl1.0-dev
但在安装 sudo apt install libssl1.0-dev 的时候 又会自动卸载掉 libssl
这样怕依赖libssl的系统其他组件有问题.

所以还是请尽快解决 libssl 依赖

**Comment by hefengxian** [comment]
感觉 Linux QT 客户端已经凉了，最新提交都是 1 月份的了，大家散了吧

**Comment by Archer456** [comment]
![default](https://user-images.githubusercontent.com/18392901/40466834-f32c73b0-5f59-11e8-832f-407047139fc7.png)
这个页面 ,突然加了ubuntu18.04的说明  还有戏,快扶我这老会员起来.....    @hefengxian

**Comment by anderslane** [comment]
下列软件包将被【卸载】：
  libssl-dev node-gyp nodejs-dev npm
下列【新】软件包将被安装：
  libssl1.0-dev

问题是npm会不能用

**Comment by altairwei** [comment]
@anderslane @hefengxian @Archer456 
你可以试试我维护的分支 https://github.com/altairwei/WizNotePlus/releases
打包了 OpenSSL v1.0.2p ，还支持多标签浏览和外部编辑器功能。

**Comment by Archer456** [comment]
> @anderslane @hefengxian @Archer456
> 你可以试试我维护的分支 https://github.com/altairwei/WizNotePlus/releases
> 打包了 OpenSSL v1.0.2p ，还支持多标签浏览和外部编辑器功能。

你好 你是wiznote的团队的人吗

**Comment by altairwei** [comment]
> > @anderslane @hefengxian @Archer456
> > 你可以试试我维护的分支 https://github.com/altairwei/WizNotePlus/releases
> > 打包了 OpenSSL v1.0.2p ，还支持多标签浏览和外部编辑器功能。
> 
> 你好 你是wiznote的团队的人吗

不是的。

**Comment by Archer456** [comment]
> > > @anderslane @hefengxian @Archer456
> > > 你可以试试我维护的分支 https://github.com/altairwei/WizNotePlus/releases
> > > 打包了 OpenSSL v1.0.2p ，还支持多标签浏览和外部编辑器功能。
> > 
> > 
> > 你好 你是wiznote的团队的人吗
> 
> 不是的。

已用上了  不错.....

**Comment by altairwei** [comment]
@Archer456 
使用中发现什么BUG可以去WizNotePlus仓库issue里提出，促进项目发展。

**Comment by Archer456** [comment]
> @Archer456
> 使用中发现什么BUG可以去WizNotePlus仓库issue里提出，促进项目发展。

好的,已经用了一阵子了. 还挺好用的,比官方 支持的好

**Comment by rikeyone** [comment]
ubuntu 18.04 对于openssl的依赖太差劲了
