### ISSUE TITLE
Network Error

### ISSUE THREAD

**Issue by r3d9u11** [WizTeam/WizQTClient#555]
Hi. I have latest version of WizNote "WizNote-2.5.9-x86_64.AppImage" on my clean Linux Mint 19 Mate.
And I can't login to my account (error "Network Error").

Temporary workaround:
1. manually download and install the .deb of older version from [PPA](https://launchpad.net/~wiznote-team/+archive/ubuntu/ppa/+packages) (it will also automatically install all needed dependencies of Qt)
2. now the newest version will work, too

**Comment by altairwei** [comment]
you need:

     sudo apt install openssl1.0 libssl1.0-dev

**Comment by r3d9u11** [comment]
@altairwei thanks for answer! Include all needed dependencies to AppImage, please (if it possible).

**Comment by altairwei** [comment]
@r3d9u11 
You can try this fork which I'm developing: https://github.com/altairwei/WizNotePlus/releases
It includes OpenSSL v1.0.2p to AppImage, and support multiple web pages viewer and external editor features.

**Comment by r3d9u11** [comment]
@altairwei thanks!
