### ISSUE TITLE
网页保存助手能否记录原始URL链接

### ISSUE THREAD

**Issue by dwSun** [WizTeam/WizQTClient#582]
如题，有些资料，其出处还有更多的资料，能否在已经保存的资料里面提供一个原始URL的记录，类似OneNote那样的。

**Comment by altairwei** [comment]
本来就会保存原始 URL 的啊，在 文档标题栏 右侧的 **查看并修改笔记属性** 里。

**Comment by dwSun** [comment]
这个位置没注意过。。。。
