### ISSUE TITLE
请求添加flatpak版本

### ISSUE THREAD

**Issue by wsgalaxy** [WizTeam/WizQTClient#587]
flatpak 把所有依赖打包，运行的兼容性比appimage版本要好。
我想询问一下上游有没有兴趣提供flathub上的官方打包，如果上游没有兴趣那么介不介意我去做一个非官方的打包？

**Comment by altairwei** [comment]
你可以自己打包：

>WizNote is an open-sourced project, published under GPLv3 for individual/personal users and custom commercial license for company users.

**Comment by cheese** [comment]
已加入 flathub 官方库 https://flathub.org/apps/details/com.wiz.Note ，该 issue 可以关闭

**Comment by wsgalaxy** [comment]
谢谢！
