### ISSUE TITLE
Cannot install plugins

### ISSUE THREAD

**Issue by MENG2010** [WizTeam/WizQTClient#607]
I am using a Linux version.

Plugin cannot be installed by dragging & dropping a wizplugin package (downloaded from Wiz site) to WizNote window. When I did this, nothing happened.

**Comment by altairwei** [comment]
WizQTClient does not support any kind of plugin and it is completely different from WizNote windows client. Therefore, you can not install wizplugin to WizQTClient.

**Comment by MENG2010** [comment]
Thanks for the prompt response.
