### ISSUE TITLE
network error 

### ISSUE THREAD

**Issue by Travis990** [WizTeam/WizQTClient#629]
![微信截图_20201002203616](https://user-images.githubusercontent.com/6883210/94923771-f8ede580-04ee-11eb-88ac-85f3e643da84.png)
version：2.8.5

**Comment by Travis990** [comment]
缺少openssl依赖库

**Comment by altairwei** [comment]
你用在 Windows 编译的？问题不仅仅是缺少 OpenSSL ，而且 GUI 相关的文件也没正确打包。

你可以试试我维护的 [WizNotePlus](https://github.com/altairwei/WizNotePlus) ，有预编译的 Windows 包，仓库的 Wiki 里面也有详细的编译教程。

**Comment by Travis990** [comment]
文件已解决
