### ISSUE TITLE
私服登录不了，不知道什么原因，网页是可以用的

### ISSUE THREAD

**Issue by jay763190097** [WizTeam/WizQTClient#646]
![image](https://user-images.githubusercontent.com/16317178/145820112-7119a37f-69df-454b-99ee-d70695df973a.png)
![image](https://user-images.githubusercontent.com/16317178/145820215-1b4d0cf9-b97c-450b-a3ce-f4abcb92e85a.png)

**Comment by altairwei** [comment]
你反馈错地方了，这个 repo 是旧的客户端，不是你第一张图片显示的 WizNote X

**Comment by jay763190097** [comment]
6000端口默认是x11的端口，chrome拦截了，更换端口就好了
