### ISSUE TITLE
Mac版本提示(当前客户端版本较低，无法编辑协作笔记 请升级客户端)

### ISSUE THREAD

**Issue by guchengod** [WizTeam/WizQTClient#650]
Mac版本同步新笔记时新的笔记提示“当前客户端版本较低，无法编辑协作笔记 请升级客户端”, 但是已经为最新版本, 旧的笔记可以查看

![image](https://user-images.githubusercontent.com/21252591/148714703-a8849dea-c3a7-4188-84b3-791c919930bb.png)

**Comment by altairwei** [comment]
它的意思是让你下载 “WizNote 重构版” ，不要再用 WizQTClient 了。:smile:

**Comment by guchengod** [comment]
> 
重构版不还是beta状态吗。这就强制让升级了????

**Comment by Steven5188** [comment]
> WizNote 重构版

你好，你用mac版本v2.8.7为知笔记客户端的话，有没有遇到"点击笔记中的同一个链接，但是浏览器中却打开两个网页"的问题呀？😊

**Comment by guchengod** [comment]
> 

确实有

**Comment by yuboabc** [comment]
这情况怎么解决啊
